apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-app
spec:
  selector:
    matchLabels:
      app: nginx-deploy-app
  template:
    metadata:
      labels:
        app: nginx-deploy-app
    spec:
      containers:
        - name: nginx-deploy-app
          image: nginx:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
