apiVersion: v1
kind: Service
metadata:
  name: nginx-deploy-app-service
spec:
  selector:
    app: nginx-deploy-app-service
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
